# Generated by Django 2.1.2 on 2018-10-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('salidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
            },
        ),
        migrations.CreateModel(
            name='FacturaEnc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_factura', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Encabezado de Factura',
                'verbose_name_plural': 'Encabezados de Facturas',
            },
        ),
        migrations.AddField(
            model_name='facturadet',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salidas.FacturaEnc'),
        ),
        migrations.AddField(
            model_name='facturadet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Producto'),
        ),
    ]
